"""Paragraph content for the HR System thesis document."""

TITLE = "An Integrated Web-Based Human Resource Recruitment and Applicant Tracking System for the Grain Marketing Board"

SUBTITLE = "A Project Report Submitted in Partial Fulfilment of the Requirements for the Development of an Enterprise Recruitment Management Solution"

ORGANIZATION = "Grain Marketing Board (GMB)"

CHAPTER_1 = {
    "1.1 Introduction": [
        "Human resource management remains one of the most critical functions within any organisation that seeks to attract, develop, and retain competent personnel. In the contemporary business environment, the recruitment process has evolved from a largely paper-based and manually coordinated activity into a technology-driven operation that demands accuracy, transparency, speed, and fairness. Organisations operating in the public sector, including parastatals and state enterprises, face additional expectations regarding accountability, auditability, and equitable access to employment opportunities. The Grain Marketing Board (GMB), as a strategic institution in the agricultural and grain marketing sector, requires a modern recruitment platform that supports its staffing needs while reflecting its institutional identity and governance standards.",
        "This project report documents the conception, planning, analysis, design, and implementation of a web-based Human Resource Recruitment and Applicant Tracking System developed for the Grain Marketing Board. The system was engineered to manage the complete recruitment lifecycle, beginning with public job advertising and online applications, continuing through curriculum vitae screening and interview scheduling, and concluding with structured interview evaluation, candidate selection, and communication with successful applicants. The solution integrates multiple user portals tailored to distinct stakeholder groups, namely job applicants, HR managers, HR staff, external interview panel members, and audit personnel.",
        "The development approach adopted for this project combined structured systems analysis with iterative implementation using modern web technologies. Python Flask was selected as the application framework due to its flexibility, readability, and suitability for rapid development of secure web applications. The resulting system stores operational data in structured JSON repositories during the prototype phase, while retaining hooks for PostgreSQL integration to support future enterprise deployment. Supplementary services for curriculum vitae scoring, document validation, and email communication were modularised to promote maintainability and extensibility.",
        "The significance of this project extends beyond the immediate automation of recruitment tasks. By centralising applications, standardising interview assessment criteria, and recording evaluator contributions from multiple interviewers, the system strengthens the evidentiary basis for hiring decisions. Furthermore, the inclusion of an audit trail, email history, and role-based access control aligns the platform with good governance practices expected of public institutions. This introductory chapter establishes the context for the study, articulates the institutional vision and values that informed the project, defines the problem domain, and presents the aims, justification, and conclusions that guide the remaining chapters of this report.",
    ],
    "1.2 Background of the Study": [
        "The Grain Marketing Board operates within a sector characterised by seasonal operational demands, geographically distributed activities, and a continuing need for skilled professionals in administration, finance, logistics, information technology, and executive leadership. Historically, recruitment within many public-sector entities has relied on manual processes including physical submission of application documents, spreadsheet-based shortlisting, telephone coordination of interviews, and paper score sheets completed by interview panels. While these methods have functioned for decades, they present well-documented limitations in scalability, traceability, and consistency.",
        "The emergence of digital government and e-recruitment initiatives globally has demonstrated that online application platforms can widen the talent pool, reduce administrative burden, and improve the candidate experience. Applicants increasingly expect to discover vacancies through public career portals, submit materials electronically, and receive timely communication regarding their application status. Concurrently, HR departments require consolidated dashboards that display application volumes, screening outcomes, interview schedules, and selection decisions without necessitating manual collation from disparate files and inboxes.",
        "Within the Zimbabwean context, institutions such as the Grain Marketing Board serve both operational and national food security objectives. Staffing decisions therefore carry implications for service delivery, regulatory compliance, and public confidence. Manual recruitment processes are vulnerable to duplication of applications, loss of curriculum vitae attachments, inconsistent interview scoring, and delays in notifying candidates. External interviewers invited to participate in selection panels often operate outside the organisation's internal network, creating further challenges for secure access and timely submission of evaluation marks.",
        "Prior to this project, recruitment activities at the organisation were characterised by fragmented workflows across email, physical documentation, and informal tracking mechanisms. HR personnel reported difficulties in determining whether a candidate had already applied for a given position, whether all interview panel members had submitted scores, and which applicants met the threshold for selection based on aggregated performance. These operational pain points provided the practical impetus for designing a unified system that could enforce business rules, preserve institutional branding, and support multi-evaluator interview processes.",
        "Academic and industry literature on Human Resource Information Systems (HRIS) and Applicant Tracking Systems (ATS) consistently emphasises the value of workflow automation, competency-based assessment, and analytics-driven shortlisting. Machine-assisted curriculum vitae screening, when implemented responsibly, does not replace human judgement but augments it by ranking candidates against stated skill requirements and experience criteria. This background establishes that the project is both timely and aligned with contemporary HR technology trends, while remaining grounded in the specific operational realities of the Grain Marketing Board.",
    ],
    "1.3 Vision": [
        "The vision guiding this project is to establish the Grain Marketing Board as a leader in transparent, efficient, and technology-enabled public-sector recruitment. The organisation aspires to provide a recruitment experience that is accessible to all qualified citizens, impartial in its evaluation processes, and exemplary in its documentation of hiring decisions. The envisioned platform serves as a digital gateway through which the institution communicates its employment opportunities, organisational culture, and commitment to merit-based selection.",
        "In the long term, the recruitment system is expected to evolve into a comprehensive talent management hub capable of supporting workforce planning, succession pipelines, and integration with broader human resource databases. The prototype implemented in this project represents the foundational layer of that vision: a secure, branded, and auditable environment where every stage of hiring is recorded, every evaluator's contribution is visible, and every candidate receives fair consideration in accordance with established criteria.",
    ],
    "1.4 Mission Statement": [
        "The mission of the Grain Marketing Board Human Resource Recruitment System is to deliver a reliable, user-centred digital platform that streamlines the end-to-end hiring process while upholding the highest standards of integrity, confidentiality, and service excellence. The system exists to empower HR professionals with actionable information, enable candidates to apply with ease, and furnish decision-makers with structured evidence to support selection outcomes.",
        "Through automation of repetitive tasks such as application capture, curriculum vitae parsing, interview invitation emailing, and score aggregation, the platform frees HR staff to concentrate on qualitative assessments and stakeholder engagement. The mission further encompasses support for external interview panels through secure, time-limited access mechanisms, thereby acknowledging that modern recruitment frequently involves independent experts who must participate without complex account provisioning or persistent credentials.",
    ],
    "1.5 Core Values": [
        "The design and implementation of the recruitment system were guided by a set of core institutional values that translate into concrete system behaviours and interface principles. Integrity is reflected in immutable activity logs, transparent recording of evaluator marks, and restrictions preventing alteration of scores after interviews are formally completed. Fairness is promoted through consistent interview criteria, averaging of marks across multiple interviewers, and enforcement of rules that prevent screening until all required evaluators have submitted their assessments.",
        "Accessibility is embodied in the public applicant portal, which allows candidates to browse vacancies, filter positions, and submit applications without requiring prior registration beyond the application form itself. The interface adopts responsive design principles and a professional colour palette to ensure usability across desktop and mobile devices. Accountability is supported through role-based access control distinguishing HR managers, HR staff, interviewers, and audit users, ensuring that each actor may perform only those actions appropriate to their responsibilities.",
        "Innovation is expressed through the incorporation of machine-learning-assisted curriculum vitae scoring, structured digital interview mark sheets, and automated email communications bearing the organisation's logo and branding. Confidentiality is maintained via secure password hashing, session management, and controlled access to uploaded documents such as curriculum vitae and certificates. Finally, excellence is pursued through continuous refinement of user experience, including branded login pages, interviewer portals aligned with HR visual identity, and clear status indicators throughout the interview lifecycle.",
        "These values are not merely declarative statements; they informed specific design decisions documented in later chapters of this report. For example, the decision to issue a single shared access code per interview panel rather than individual permanent passwords for external interviewers balances security with operational practicality, reducing onboarding friction while preserving time-bound access. Similarly, the requirement that all panel members submit marks before HR may conduct final screening encodes fairness directly into the system's business logic.",
    ],
    "1.6 System Request": [
        "The system request originated from the Human Resources department of the Grain Marketing Board, which identified an urgent need to modernise recruitment operations in response to increasing application volumes and the complexity of multi-stage selection processes. The department formally requested a bespoke web application that would consolidate applicant data, support executive and specialist recruitment campaigns, and provide a professional public-facing careers portal consistent with the organisation's corporate identity.",
        "The request specified several mandatory capabilities. First, the system should allow HR personnel to publish job vacancies with descriptions, departments, deadlines, and the number of positions sought. Second, applicants should be able to submit personal details, educational background, curriculum vitae, and supporting certificates through an online form. Third, HR users should be able to screen applicants using automated curriculum vitae scoring supplemented by manual review. Fourth, the system should support interview scheduling with email notifications, interviewer panel management, structured scoring across seven evaluation criteria, and final selection of candidates based on highest average scores.",
        "Additional requirements included branding customisation (logo, welcome imagery, welcome video), SMTP-based email delivery, duplicate application prevention, audit logging, and a dedicated interviewer portal for external panel members. The requesting department emphasised that the solution should be deployable on standard organisational infrastructure and maintainable by internal or contracted IT personnel with Python and web development competencies.",
    ],
    "1.7 Problem Definition": [
        "The fundamental problem addressed by this project is the absence of an integrated, rule-enforced, and auditable digital platform for managing recruitment at the Grain Marketing Board. Without such a platform, HR staff must coordinate hiring using disconnected tools that were not designed for end-to-end workflow management. This fragmentation produces inefficiency, increases the risk of error, and weakens the organisation's ability to demonstrate that selection processes were conducted fairly and in accordance with stated criteria.",
        "Several specific sub-problems were identified during preliminary consultations. Application duplication occurs when candidates submit multiple entries for the same vacancy through different channels, creating confusion during shortlisting. Document management challenges arise when curriculum vitae files are stored in unstructured folders or email attachments, making retrieval during interviews difficult. Interview coordination problems emerge when multiple candidates are scheduled across different dates and panel members lack a unified interface for submitting scores.",
        "A particularly acute sub-problem concerns multi-interviewer evaluation. When several external experts assess candidates for senior positions, each interviewer may apply personal scoring templates or submit marks informally through email or handwritten forms. Aggregating these scores manually is time-consuming and prone to transcription errors. Furthermore, premature declaration of interview completion—before all panel members have submitted marks—can undermine the validity of selection decisions.",
        "Communication gaps represent another dimension of the problem. Candidates frequently experience uncertainty regarding their application status, interview schedules, and final outcomes when notifications are sent inconsistently or not at all. Internal stakeholders, including audit personnel, may lack visibility into who performed which actions and when, complicating post-hoc review of recruitment campaigns.",
        "The problem definition may therefore be summarised as follows: the Grain Marketing Board requires a centralised recruitment information system that automates application capture, enforces sequential and collaborative interview workflows, aggregates multi-evaluator scores using transparent averaging methods, and maintains comprehensive records suitable for operational review and compliance purposes.",
    ],
    "1.8 Aim and Objectives": [
        "The primary aim of this project is to design and implement a web-based Human Resource Recruitment and Applicant Tracking System that improves the efficiency, transparency, and reliability of hiring processes at the Grain Marketing Board.",
        "To achieve this aim, the project pursued the following objectives: to develop a public applicant portal for vacancy publication and online applications; to implement secure authentication and role-based access for HR managers, HR staff, external interviewers, and audit users; to integrate automated curriculum vitae screening using text analysis and skill matching techniques; to enable interview scheduling with configurable email invitations; to support external interviewer panels through shared secure access links and one-time panel access codes; to record individual evaluator marks across seven standardised criteria and compute average scores across interviewers; to enforce business rules ensuring that screening and selection occur only after all required evaluators have submitted marks for all interviewed candidates; to provide branding and settings management for institutional logo, welcome media, and mail server configuration; and to maintain activity logs and email history for audit purposes.",
        "Secondary objectives included delivering a professional user interface aligned with the organisation's colour scheme and visual identity, ensuring mobile responsiveness, and producing comprehensive project documentation to support future maintenance, enhancement, and academic assessment of the work.",
    ],
    "1.9 Justification": [
        "The justification for undertaking this project rests on operational, economic, governance, and educational grounds. Operationally, the system reduces the time required to collate applications, identify duplicate submissions, schedule interviews, and aggregate panel scores. HR personnel can view a consolidated dashboard rather than navigating multiple spreadsheets and email threads. Automated curriculum vitae scoring accelerates initial shortlisting while preserving the option for manual review, thereby improving throughput during high-volume recruitment drives.",
        "From an economic perspective, although the development of a bespoke system incurs initial implementation costs, the reduction in manual labour, printing, physical storage, and repeated communication efforts yields medium-term savings. Errors that might necessitate re-interviewing candidates or rectifying wrongful selections carry reputational and potential legal costs that the system helps mitigate through structured workflows and complete records.",
        "Governance justification is particularly compelling for a public-sector institution. The platform's activity logs, per-evaluator mark visibility, and prevention of post-completion score editing create an evidence trail that supports internal audit and external scrutiny. The sequential interview model—where HR activates one candidate at a time and interviewer portals refresh automatically—mirrors controlled boardroom practices and minimises confusion among panel members.",
        "Educationally, the project demonstrates the application of systems analysis, software engineering, database design, human-computer interaction, and machine learning concepts within a real organisational context. It provides a reference implementation for students and practitioners interested in HR technology solutions within developing economies and public-sector environments.",
        "Finally, the project is justified by user demand: candidates increasingly prefer digital application channels, and HR professionals require modern tools to manage competency-based selection. Failure to modernise recruitment infrastructure risks talent loss to competing employers that offer streamlined application experiences, ultimately affecting the Grain Marketing Board's ability to attract qualified personnel.",
    ],
    "1.10 Chapter Summary and Conclusion": [
        "This chapter has introduced the Grain Marketing Board Human Resource Recruitment System within its organisational and technological context. The background of the study highlighted limitations of manual recruitment processes and the growing importance of integrated applicant tracking solutions. The vision, mission, and values articulated herein shaped both functional requirements and ethical design choices throughout the project lifecycle.",
        "The system request and problem definition established a clear mandate for a multi-portal web application capable of managing applications, screening, interviews, collaborative scoring, and selection. The stated aim and objectives provide measurable targets against which the success of subsequent planning, analysis, design, and implementation activities may be evaluated. The justification affirmed that the project addresses genuine operational needs while contributing to governance and academic knowledge.",
        "In conclusion, Chapter One demonstrates that the development of this recruitment platform is both necessary and feasible. The remaining chapters of this report document how the project team translated this foundational understanding into a structured plan, rigorous requirements analysis, detailed system design, and working implementation that collectively fulfil the objectives set forth at the outset.",
    ],
}

CHAPTER_2 = {
    "2.1 Introduction to Project Planning": [
        "Project planning constitutes the bridge between problem identification and successful system delivery. For the Grain Marketing Board recruitment system, planning activities encompassed definition of scope, identification of stakeholders, scheduling of development phases, allocation of resources, assessment of risks, and evaluation of feasibility across technical, operational, and economic dimensions. Effective planning ensured that the development team maintained focus on deliverables that directly addressed the HR department's priorities while avoiding uncontrolled feature expansion that could delay deployment.",
        "This chapter describes the planning framework applied to the project, including the work breakdown structure, timeline, stakeholder engagement strategy, and risk mitigation measures. It also documents the feasibility analysis that supported the selection of Python Flask as the primary development framework and JSON-based persistence for the prototype phase.",
    ],
    "2.2 Project Scope": [
        "The scope of the project was defined to include all core activities associated with electronic recruitment management for the Grain Marketing Board prototype environment. In-scope elements comprised the applicant careers portal, HR management dashboard, external interviewer portal, audit access module, curriculum vitae upload and storage, automated CV scoring service, interview scheduling and notification, multi-evaluator mark capture, screening and selection logic, branding configuration, user management, activity logging, and email history tracking.",
        "Explicitly excluded from the initial scope were payroll integration, post-employment onboarding workflows, performance appraisal modules, and full enterprise PostgreSQL migration, although architectural provisions were made for future database integration. Mobile native applications were likewise out of scope; however, responsive web design was required to support mobile browser access. The scope statement was reviewed with HR stakeholders to confirm alignment with immediate operational needs.",
        "Scope management procedures required that any proposed enhancement—such as SMS notifications or integration with national employment registries—be evaluated against timeline and resource constraints before acceptance. This discipline preserved delivery of a functional minimum viable product within the academic project timeframe.",
    ],
    "2.3 Stakeholder Identification and Engagement": [
        "Successful recruitment systems depend on the active participation of diverse stakeholders. Primary stakeholders included HR managers responsible for policy and final selection decisions, HR staff conducting screening and interview coordination, job applicants seeking employment, external interview panel members providing independent assessments, and audit personnel reviewing process integrity. Secondary stakeholders encompassed IT support staff, organisational leadership, and academic supervisors overseeing the project.",
        "Engagement strategies varied by stakeholder group. HR managers participated in requirements workshops and user acceptance testing. HR staff provided feedback on dashboard layout and workflow sequencing. Applicants were considered through usability principles applied to the careers portal design. External interviewers informed the design of simplified sign-in using name and panel access code. Audit stakeholders influenced the inclusion of comprehensive logging and non-repudiation of completed interview records.",
        "A stakeholder matrix was maintained mapping influence, interest, and communication frequency. High-influence, high-interest stakeholders such as HR managers received weekly progress updates during intensive development periods. Interviewers received targeted documentation explaining portal usage during panel recruitment campaigns.",
    ],
    "2.4 Project Timeline and Development Phases": [
        "The project was organised into five sequential phases aligned with the chapters of this report: initiation and planning, systems analysis, system design, implementation, and testing with documentation. The initiation phase involved background research, stakeholder consultations, and preparation of the project proposal. The analysis phase produced requirements specifications, process models, and data dictionaries. The design phase yielded architecture diagrams, interface mock-ups, module specifications, and security plans.",
        "Implementation was subdivided into backend route development, template construction, service module integration, and data migration scripting. Testing ran concurrently with implementation through iterative verification of individual modules. A concluding documentation phase produced user guides, technical documentation, and this formal project report.",
        "Although academic deadlines imposed a compressed calendar relative to enterprise projects, the phased structure mirrored industry best practice and enabled parallel work where dependencies allowed—for example, frontend template design proceeded once core API endpoints were defined.",
    ],
    "2.5 Resource Planning": [
        "Human resources for the project consisted of the lead developer responsible for full-stack implementation, academic supervision providing methodological guidance, and HR domain experts supplying requirements validation. Material resources included development workstations running Microsoft Windows, Python 3.11 runtime environment, Visual Studio Code integrated development environment, and local server infrastructure for testing at localhost port 5000.",
        "Software resources encompassed Flask web framework, Werkzeug security utilities, scikit-learn for curriculum vitae scoring, python-docx and PyPDF libraries for document parsing, and Git for version control. Network resources included SMTP mail server access for email notification testing. Storage resources comprised local directories for JSON data persistence and uploaded applicant documents.",
        "Resource planning also accounted for documentation assets stored under docs/images for screenshots and uploads/branding for institutional media. Contingency resources included backup copies of data directories to prevent loss during testing iterations.",
    ],
    "2.6 Risk Management": [
        "Risk management activities identified potential threats to project success and defined mitigation strategies. Technical risks included email delivery failures due to misconfigured SMTP credentials, mitigated by providing settings UI and environment variable templates. Data loss risk arising from JSON file corruption was mitigated through regular backup of the data directory and atomic save operations where feasible.",
        "Security risks such as unauthorised access to HR functions were addressed through password hashing, session management, and role checks on protected routes. Operational risks included external interviewers failing to submit marks before selection deadlines, mitigated by pending-evaluator indicators and screening guards that block premature completion.",
        "Project management risks such as scope creep were controlled through formal change evaluation. Academic risks including timeline overruns were mitigated by prioritising core workflows over cosmetic enhancements until baseline functionality was verified.",
    ],
    "2.7 Feasibility Study": [
        "A feasibility study was conducted across technical, operational, economic, and schedule dimensions. Technical feasibility was confirmed by successful prototyping of Flask routes, JSON persistence, CV parsing, and email sending using readily available open-source libraries. Operational feasibility was established through walkthroughs with HR stakeholders who confirmed that proposed workflows matched actual recruitment practices, including board-style interviews with external experts.",
        "Economic feasibility favoured in-house development over commercial ATS licensing, which often entails recurring subscription costs unsuitable for single-organisation deployment in resource-constrained environments. Schedule feasibility acknowledged constraints but deemed achievable given modular architecture and reuse of existing HTML/CSS frameworks.",
        "Legal and ethical feasibility considerations included fair processing of applicant personal data, consent implied through voluntary application submission, and secure storage of curriculum vitae files with access restricted to authorised HR users.",
    ],
    "2.8 Project Management Methodology": [
        "The project adopted an incremental and iterative methodology combining elements of structured systems development with agile feedback loops. Each module was implemented in vertical slices—backend logic, template rendering, and basic testing—before progressing to dependent modules. This approach reduced integration risk and enabled early demonstration to stakeholders.",
        "Version control practices tracked changes to app.py, templates, services, and data schemas. Issue prioritisation classified defects as critical, major, or minor based on impact on hiring workflows. Meetings with supervisors provided milestone reviews at the conclusion of each chapter-equivalent phase.",
    ],
    "2.9 Chapter Summary": [
        "Chapter Two has presented the planning foundations upon which the Grain Marketing Board recruitment system was executed. Scope definition, stakeholder engagement, scheduling, resource allocation, risk management, and feasibility analysis collectively ensured that the project proceeded with clear boundaries and realistic expectations. The planning outputs directly informed the requirements analysis and design activities documented in Chapters Three and Four.",
    ],
}

CHAPTER_3 = {
    "3.1 Introduction to Systems Analysis": [
        "Systems analysis transforms stakeholder needs and problem definitions into precise, verifiable requirements that guide design and implementation. For the recruitment platform, analysis involved examination of existing manual processes, identification of data entities and relationships, specification of functional and non-functional requirements, and modelling of workflows for applicants, HR users, interviewers, and auditors. This chapter documents the analytical artefacts and reasoning that underpin the implemented solution.",
    ],
    "3.2 Analysis of the Existing System": [
        "The existing recruitment environment prior to this project was characterised as a manual, distributed system without a central database. Job advertisements were disseminated through institutional websites, printed notices, and informal channels. Applicants submitted physical or email-based application packages that HR officers downloaded or filed manually. Shortlisting relied on subjective review of curriculum vitae without standardised scoring metrics.",
        "Interview invitations were composed individually in email clients, sometimes resulting in inconsistent messaging or omission of key logistical details. Interview panels recorded scores on paper forms that were collected after sessions and manually averaged by HR staff. External interviewers experienced delays receiving credentials or instructions, and their marks occasionally arrived after selection meetings had already concluded.",
        "The existing system's data flows were poorly documented, and audit reconstruction required interviewing staff and searching email archives. This analysis confirmed a substantial gap between current capabilities and desired state, validating investment in a purpose-built applicant tracking platform.",
    ],
    "3.3 Requirements Gathering Techniques": [
        "Requirements were gathered through structured interviews with HR personnel, direct observation of recruitment files and templates, review of sample curriculum vitae and job descriptions, and analysis of comparable ATS products. Prototype screens were presented iteratively to collect feedback on terminology, colour schemes, and workflow ordering. Use cases were drafted for each actor describing preconditions, main flows, and exception conditions.",
        "The requirements gathering process also incorporated lessons from testing early prototypes, which revealed needs such as duplicate application prevention, sequential active-candidate control for interviewers, and visibility of pending evaluator submissions on the HR marks board.",
    ],
    "3.4 Functional Requirements": [
        "Functional requirements specify observable system behaviours. The applicant portal shall display open job vacancies with search and filter capabilities; allow submission of applications with personal data, education level, curriculum vitae, and certificates; and prevent duplicate applications from the same email address for the same job. The HR portal shall support job creation with title, description, department, deadline, and positions needed; display dashboards of applications and interview queues; execute CV screening manually or automatically; schedule interviews with date, time, type, location, and personalised messages; send email invitations when SMTP is configured; manage external interviewers per job; generate shared interviewer links with time-limited access codes; start interviews for one active candidate at a time; record marks across seven criteria; display per-evaluator mark breakdown; block screening until all panel interviewers have scored all interviewed candidates; rank candidates by average score; and select the highest-ranked applicants up to the number of positions required.",
        "The interviewer portal shall authenticate using registered name and panel access code; display only the currently active candidate; auto-refresh when HR starts a new candidate; allow mark submission and updates until interviews are completed; and prevent scoring of inactive candidates. The audit portal shall provide access to activity logs and compliance views. Settings shall allow upload of company logo, welcome image, welcome video, and mail configuration.",
    ],
    "3.5 Non-Functional Requirements": [
        "Non-functional requirements address quality attributes. Performance requirements specify that dashboard pages should load within acceptable time on standard organisational hardware for datasets up to several thousand applications. Security requirements mandate hashed passwords, HTTP-only session cookies, role-based authorisation, and sanitised file uploads. Usability requirements call for consistent branding using teal (#124e66), navy (#0a2338), and orange (#f39c12) palette across portals.",
        "Reliability requirements include graceful handling of missing SMTP configuration with user-visible warnings. Maintainability requirements favour modular services for CV scoring and email. Portability requirements target deployment on Windows Server or Linux with Python 3.11. Scalability requirements anticipate future migration from JSON files to PostgreSQL without rewriting business logic.",
    ],
    "3.6 Data Analysis and Entity Identification": [
        "Data analysis identified primary entities: Users, Jobs, Applications, Interviewer Panels, Activity Logs, Email History, and Settings. Users possess roles, credentials, permissions, and optional interviewer job assignments. Jobs contain descriptive fields, deadlines, and position counts. Applications store candidate demographics, document paths, screening scores, interview schedules, status fields, evaluator submissions, and selection flags.",
        "Interviewer Panels associate job identifiers with interviewer user lists, shared tokens, access codes, active application identifiers, and expiry timestamps. Relationships include one-to-many from jobs to applications, many-to-many between panels and interviewers, and one-to-many from applications to score submissions.",
    ],
    "3.7 Business Process Analysis": [
        "The to-be business process begins with HR publishing a vacancy. Applicants discover and apply through the portal. HR screens applications, advancing qualified candidates to interview status. HR schedules interviews and notifies candidates via email. HR registers external interviewers and distributes shared link and access code. For each candidate, HR starts the interview session, panel members submit marks, and the system tracks evaluator completion. After all candidates are interviewed and all marks collected, HR executes screening to rank by average score and confirms selection of top candidates. Rejected or unsuccessful applicants may receive notification emails.",
        "This process model replaced ambiguous transitions in the as-is system with explicit statuses: scheduled, in progress, awaiting screening, and completed.",
    ],
    "3.8 Gap Analysis": [
        "Gap analysis compared as-is and to-be states across dimensions of data centralisation, automation, collaboration, communication, and auditability. The largest gaps existed in collaborative interview scoring and rule-enforced screening. The proposed system closes these gaps through interviewer panels, per-evaluator submission records, averaging logic, and screening guards.",
    ],
    "3.9 Chapter Summary": [
        "Chapter Three has presented comprehensive systems analysis for the Grain Marketing Board recruitment platform. Existing process limitations were documented, requirements were specified, data entities were identified, and business processes were modelled. These analytical outputs provided the necessary foundation for detailed system design in Chapter Four.",
    ],
}

CHAPTER_4 = {
    "4.1 Introduction to System Design": [
        "System design translates analysed requirements into blueprints describing architecture, data structures, interfaces, modules, and security controls. Design activities for the Grain Marketing Board recruitment system emphasised modularity, clarity of user experience, and enforceability of recruitment business rules. This chapter presents the high-level architecture, database design, interface design, module decomposition, and specialised designs for interview panels, curriculum vitae scoring, and email communications.",
    ],
    "4.2 System Architecture": [
        "The system follows a three-tier web architecture comprising presentation, application, and data layers. The presentation layer consists of Jinja2 HTML templates styled with CSS and minimal client-side JavaScript for dashboard interactivity, modal dialogs, and interviewer portal polling. The application layer is implemented in a monolithic Flask application (app.py) exposing routes for each portal and JSON APIs for asynchronous operations. The data layer initially comprises JSON files in the data directory loaded into in-memory dictionaries at startup and persisted on updates, with auxiliary file storage in uploads for binary documents.",
        "Supplementary service modules in the services package encapsulate curriculum vitae scoring, document validation, and email helper functions, promoting separation of concerns. A context processor injects branding variables such as portal logo source and company display name into all templates for consistent identity presentation.",
    ],
    "4.3 Database and Data Structure Design": [
        "Although the prototype employs JSON persistence, the logical database schema was designed relationally to support future migration. Tables correspond to users, jobs, applications, interviewer_panels, activity_logs, email_history, and settings key-value records. Applications embed nested structures for interview_scores and interview_score_submissions arrays capturing per-evaluator marks and timestamps.",
        "File path references within application records point to curriculum vitae and certificate documents stored under uploads with naming conventions incorporating application identifiers. Interviewer panel records track active_application_id and active_changed_at to synchronise sequential interview workflows across HR and interviewer interfaces.",
    ],
    "4.4 User Interface and Experience Design": [
        "Interface design prioritised professional appearance appropriate to a public-sector grain marketing institution. The HR login page employs a centred card layout with gradient header in teal and navy, orange accent icons, and uploaded company logo. The HR dashboard uses a sidebar navigation pattern with sections for jobs, screening, interviews, interview marks, selected candidates, settings, and reports.",
        "The applicant portal presents welcome media, job cards, and search filters within a responsive grid. The interviewer portal mirrors HR colour themes rather than using a disconnected dark theme, reinforcing institutional consistency. Form controls use clear labelling, inline validation, and accessible contrast ratios.",
    ],
    "4.5 Module Design": [
        "The Authentication Module handles login, logout, session establishment, and role-based redirection to HR, audit, or interviewer interfaces. The Job Management Module supports CRUD operations on vacancies with deadline state computation. The Application Module processes apply form submissions, stores documents, prevents duplicates, and enriches records with display names and job titles.",
        "The Screening Module invokes CV scoring services and updates application status and recommendations. The Interview Module manages scheduling, start and end session actions, cancellation, and queue removal. The Scoring Module upserts per-evaluator submissions, recomputes averages, synchronises interview status, and blocks edits after completion. The Interviewer Panel Module manages interviewer registration, link generation, access codes, and active candidate assignment. The Selection Module ranks completed candidates and marks top applicants as selected. The Settings Module persists branding and SMTP configuration. The Audit Module exposes activity and email history.",
    ],
    "4.6 Security Design": [
        "Security design incorporates password hashing via Werkzeug PBKDF2 methods, non-permanent session cookies cleared on browser close, HTTP-only and SameSite cookie attributes, after-request security headers including X-Content-Type-Options and X-Frame-Options, role decorators on sensitive routes, and secure filename handling for uploads. Interviewer access uses time-limited tokens and single shared access codes rather than distributing long-lived credentials.",
    ],
    "4.7 Interview Panel and Sequential Workflow Design": [
        "Interview panel design centres on INTERVIEWER_PANELS data structure keyed by job identifier. HR adds interviewers by name and email, creating user accounts with interviewer role and job assignment. Link generation creates UUID tokens, eight-digit access codes, and twenty-four-hour expiry timestamps. When HR starts an interview, the panel's active_application_id updates, triggering interviewer portal refresh via polling endpoint /interviewer/api/active-candidate.",
        "Scoring design records each evaluator's marks separately. Average computation aggregates totals across submissions. Screening design requires all queued candidates to have started interviews and received complete panel marks before HR may execute screen operation, at which point candidates transition to completed status and become eligible for ranked selection by highest average.",
    ],
    "4.8 Curriculum Vitae Scoring Design": [
        "The CV scoring service extracts text from PDF and DOCX curriculum vitae files, tokenises content, compares against job description keywords and skill taxonomies using TF-IDF vectorisation and cosine similarity, evaluates experience and education alignment heuristically, and produces numeric scores with matched and missing skill lists and textual recommendations. This design augments HR judgement without removing human oversight from final screening decisions.",
    ],
    "4.9 Email System Design": [
        "Email design supports multipart HTML messages with embedded company logo content identifiers, configurable SMTP parameters from settings and environment variables, templated interview invitation messages with placeholder substitution for candidate name, job title, date, time, type, and location, and logging of sent messages to email_history for later review.",
    ],
    "4.10 Chapter Summary": [
        "Chapter Four has articulated the design of the Grain Marketing Board recruitment system across architectural, data, interface, module, security, workflow, scoring, and communication dimensions. The design artefacts serve as direct specifications for implementation activities described in Chapter Five.",
    ],
}

CHAPTER_5 = {
    "5.1 Introduction to Implementation": [
        "Implementation represents the materialisation of planning, analysis, and design artefacts as functioning software. This chapter describes the development environment, implementation of major modules, testing procedures, deployment considerations, challenges encountered, and overall project outcomes for the Grain Marketing Board Human Resource Recruitment System.",
    ],
    "5.2 Development Environment and Tools": [
        "Development was conducted on Microsoft Windows workstations using Python 3.11, Flask 3.x framework, and Visual Studio Code editor. Dependency management relied on requirements.txt enumerating packages including Flask, Werkzeug, scikit-learn, python-docx, pypdf, Pillow, and python-docx. Local execution used Flask development server binding to 0.0.0.0:5000 for network testing. Environment variables in .env supplied SECRET_KEY and SMTP credentials. Git version control tracked source changes.",
    ],
    "5.3 Implementation of Core Modules": [
        "The core application file app.py implements route handlers, data loading and saving functions, enrichment utilities, permission decorators, and business logic guards. On startup, load_all_data reads JSON files into global dictionaries and performs schema backfill migrations for new fields such as interview_score_submissions and panel access codes. The applicant-facing routes render index.html and apply.html, processing multipart form uploads and invoking duplicate detection logic.",
        "HR routes under /hr render hr_dashboard.html with embedded sections for jobs, screening, interviews, interview marks, and settings modals. JSON endpoints support asynchronous interviewer management, link generation, interview lifecycle actions, scoring, screening, and selection. The interviewer routes implement join authentication and dashboard rendering filtered to active candidates. CV scoring integration calls services/cv_scoring.py during screening operations.",
    ],
    "5.4 Implementation of Interview and Scoring Logic": [
        "Interview implementation enforces sequential active candidate control through _set_active_interview helper updating panel state and synchronising statuses of previously active applications. The hr_start_interview endpoint activates candidates; hr_score_interview records evaluator submissions via _upsert_interview_score_submission; _sync_interview_status_after_score transitions statuses based on evaluator completion; hr_screen_interviews validates all candidates and all panel marks before marking completed and returning rankings sorted by interview_average; hr_select_best_candidates selects top applicants by average with tie-breaking support.",
        "Frontend implementation in hr_dashboard.html renders evaluator mark tables with pending interviewer indicators and average summary rows. interviewer_dashboard.html polls active candidate API every five seconds and reloads when active_changed_at differs, ensuring panel members automatically see newly started candidates.",
    ],
    "5.5 Testing": [
        "Testing combined unit-level verification of helper functions, integration testing of route responses, and manual user acceptance testing with HR stakeholders. Test cases included successful and failed login, job posting, application submission, duplicate application rejection, CV screening, interview scheduling email, interviewer join with valid and invalid access codes, mark submission from multiple interviewers, screening blocked with incomplete marks, successful screening with complete marks, and selection of highest average candidates.",
        "Defects discovered during testing led to corrections such as preventing premature completed status after single evaluator submission, removing edit options after completion, and requiring all candidates to finish before screening.",
    ],
    "5.6 Deployment Considerations": [
        "Deployment guidance recommends production hosting behind Gunicorn or Waitress WSGI server with HTTPS termination, migration to PostgreSQL for concurrent access, scheduled backup of data and uploads directories, secure secret management, and rate limiting on authentication endpoints. Environment-specific configuration should be separated from source control to protect SMTP credentials.",
    ],
    "5.7 Challenges and Solutions": [
        "Challenges included SMTP configuration complexity, synchronising multi-interviewer workflows, and maintaining JSON data consistency during concurrent development tests. Solutions encompassed settings UI with test email function, panel active candidate architecture with polling refresh, and save routines invoked after each state mutation.",
    ],
    "5.8 Chapter Summary and Overall Conclusion": [
        "Chapter Five has documented the implementation and validation of the Grain Marketing Board recruitment system. The delivered platform fulfils the objectives stated in Chapter One by providing integrated applicant tracking, automated screening support, collaborative interview evaluation, and rule-governed selection based on average scores.",
        "In overall conclusion, this project demonstrates that a bespoke HR recruitment system tailored to public-sector requirements can be successfully developed using open-source technologies within academic project constraints. The system improves transparency by showing which interviewer awarded which marks, improves fairness by averaging across evaluators, improves efficiency by automating notifications and document management, and improves governance through logging and status enforcement.",
        "Future work may encompass PostgreSQL migration, SMS notifications, advanced analytics dashboards, integration with national employment platforms, and mobile applications. Nonetheless, the current implementation provides a robust and extensible foundation upon which the Grain Marketing Board can modernise its recruitment operations and reinforce public confidence in its hiring practices.",
    ],
}
