"""Further content blocks to reach ~50 pages."""

LITERATURE_REVIEW = {
    "1.11 Literature Review": [
        "The academic literature on Human Resource Information Systems establishes that technology-enabled recruitment can significantly influence both process efficiency and perceived organisational professionalism. Laudon and Laudon (2020) emphasise that enterprise systems must align with business processes rather than forcing users to adapt to arbitrary software structures. This principle informed the decision to model interview workflows around actual GMB panel practices, including sequential candidate activation and external evaluator participation.",
        "Research on Applicant Tracking Systems by researchers in information systems highlights common functional modules: requisition management, candidate relationship management, interview scheduling, and compliance reporting. Commercial systems such as those offered by global HR technology vendors provide extensive integrations but may not accommodate local public-sector hiring conventions without expensive customisation. Open-source frameworks offer an alternative pathway for institutions willing to invest in bespoke development guided by structured analysis.",
        "Studies on curriculum vitae parsing and automated ranking demonstrate that text mining techniques including Term Frequency-Inverse Document Frequency (TF-IDF) vectorisation and cosine similarity can produce useful preliminary rankings when job descriptions contain explicit skill requirements. However, scholars caution against fully automated rejection decisions because semantic nuance, contextual experience, and non-standard career paths may be underrepresented in keyword models. The GMB system therefore treats automated scoring as decision support for HR reviewers who retain authority to advance or reject candidates manually.",
        "Literature on collaborative decision-making in hiring committees underscores the importance of aggregating independent judgements to reduce individual bias. Averaging normalised scores across multiple interviewers is a straightforward aggregation method comprehensible to audit stakeholders, though organisations may alternatively employ weighted averages or deliberative consensus sessions. The implemented system computes arithmetic means transparently displayed on HR mark sheets.",
        "Security literature relevant to web-based HR systems addresses authentication, authorisation, session hijacking prevention, and protection of personally identifiable information. Password hashing using PBKDF2 or bcrypt is widely recommended over reversible encryption or plaintext storage. Role-based access control models map organisational roles to permission sets; the GMB platform distinguishes HR managers, HR staff with granular screening and scoring permissions, interviewers with limited scoring rights on active candidates only, and audit users with read-oriented access.",
        "User experience research indicates that visual consistency and institutional branding on public careers pages influence applicant trust. Applicants associate polished interfaces with organisational competence. Conversely, broken links, unstyled forms, or non-responsive layouts may discourage qualified candidates from completing applications. The project's adoption of consistent teal, navy, and orange branding across applicant, HR, and interviewer portals responds to these findings.",
        "Finally, project management literature supports phased delivery and stakeholder engagement as predictors of information systems success. The structured chapter progression of this report mirrors classic waterfall phases while allowing iterative refinement within implementation. This hybrid approach is common in academic software engineering projects constrained by semester or term deadlines.",
    ],
}

EXTENDED_APPENDICES = {
    "Appendix D: Detailed Module Specifications": [
        "Module: Authentication and Session Management. Inputs: email and password via POST login form. Processing: lookup user record, verify password hash, establish session user_id without permanent session flag. Outputs: redirect to HR dashboard, audit dashboard, or error flash message. Exceptions: invalid credentials, missing fields, inactive accounts.",
        "Module: Job Posting. Inputs: title, description, department, due date, positions needed. Processing: generate UUID job identifier, persist to jobs.json, compute deadline state. Outputs: updated jobs list on dashboard. Validation: required fields non-empty, positions needed positive integer.",
        "Module: Application Capture. Inputs: multipart form with personal data and files. Processing: duplicate check by email and job_id, secure filename generation, CV path storage, initial status pending. Outputs: success page or validation error. Security: file type restrictions, size considerations.",
        "Module: CV Screening Service. Inputs: application record with resume path and job description text. Processing: extract text from PDF/DOCX, compute skill matches, experience and education heuristics, TF-IDF similarity. Outputs: numeric score, matched skills array, missing skills array, recommendation string.",
        "Module: Interview Scheduling. Inputs: candidate identifier, date, time, type, location, message template, send_email flag. Processing: update application interview fields, set status interview, optionally compose and send HTML email. Outputs: JSON success with enriched application.",
        "Module: Interviewer Panel Management. Inputs: interviewer name, email, job_id. Processing: create interviewer user with job assignment, append to panel interviewer_ids. Link generation creates token, access code, expiry. Outputs: JSON panel summary for dashboard display.",
        "Module: Active Interview Control. Inputs: application id on start endpoint. Processing: update panel active_application_id, set target in_progress, reconcile previous active candidate status. Outputs: enriched application JSON. Side effect: interviewer polling detects active_changed_at.",
        "Module: Score Submission. Inputs: seven criterion integers zero to twenty. Processing: validate bounds, upsert submission by scorer_id, recompute average total, sync status. Outputs: updated application. Guards: reject if completed, reject interviewer if not active candidate.",
        "Module: Screening and Selection. Inputs: job_id, positions_needed. Processing: verify all interviewed candidates have full panel marks, mark completed, sort by average, select top N with tie handling. Outputs: ranked list or error describing pending evaluators.",
    ],
    "Appendix E: Interview Evaluation Criteria Rubric": [
        "Presentation (0-20): Assesses clarity of self-introduction, structure of responses, and professional demeanour during opening interactions. Dressing (0-20): Assesses appropriateness of attire relative to organisational standards and role seniority. Communication (0-20): Assesses articulation, listening skills, and responsiveness to questions.",
        "Confidence (0-20): Assesses composure under questioning without conflating confidence with aggression. Technical Knowledge (0-20): Assesses domain understanding relevant to the advertised role, including sector-specific awareness where applicable. Problem Solving (0-20): Assesses analytical approach to scenario-based or competency questions.",
        "Attitude (0-20): Assesses interpersonal respect, enthusiasm for the organisation, and alignment with stated values. Total percentage normalises sum of criteria to a 140-point scale, enabling comparison across candidates and across evaluators. HR training materials should calibrate panel members to apply criteria consistently.",
    ],
    "Appendix G: Glossary of Terms": [
        "Applicant Tracking System (ATS): Software managing recruitment from job posting through hiring decision.",
        "Curriculum Vitae (CV): Document summarising applicant education, experience, and skills submitted during application.",
        "Evaluator: Any user submitting interview marks, including HR staff and external interviewers.",
        "Interview Panel: Group of interviewers assigned to assess candidates for a specific job vacancy.",
        "Screening: Process of reviewing applications or interview outcomes to advance or select candidates.",
        "TF-IDF: Term Frequency-Inverse Document Frequency, statistical measure used in text similarity scoring.",
        "JSON: JavaScript Object Notation format used for prototype data persistence in this project.",
        "SMTP: Simple Mail Transfer Protocol used for sending email notifications.",
        "Role-Based Access Control: Security model granting permissions based on user role assignments.",
        "Active Candidate: The single candidate currently being interviewed as designated by HR start action.",
        "Access Code: Eight-digit one-time panel code shared by external interviewers for authentication.",
        "Average Score: Arithmetic mean of total percentage marks submitted by all required evaluators for a candidate.",
    ],
    "Appendix H: Case Study Walkthrough": [
        "This appendix narrates a end-to-end case study for a Chief Executive Officer recruitment campaign at the Grain Marketing Board using the implemented system. The narrative demonstrates practical interaction sequences and expected system states at each step.",
        "Step one: HR Manager logs into the HR portal and navigates to Jobs. A new vacancy is created with title Chief Executive Officer, comprehensive role description, executive department classification, application deadline two weeks forward, and positions needed equal to one. The job appears on the public careers portal with open deadline state.",
        "Step two: Over the application period, multiple candidates submit online applications uploading curriculum vitae files. The system rejects duplicate email applications for the same job while accepting applications from the same person for different jobs if applicable. Each successful submission creates an application record with pending status and stored document paths.",
        "Step three: After deadline, HR executes screening for the CEO job. Automated CV scoring ranks candidates. HR reviews recommendations, manually screens borderline cases, and advances top candidates to interview status. Rejected candidates may receive optional rejection emails.",
        "Step four: HR schedules interviews assigning date, time, in-person type, boardroom location, and personalised email message. Candidates receive HTML invitations embedding the company logo. Interview records show scheduled status in HR interview table.",
        "Step five: HR registers external interviewers Dr. Arthur and Prof. Chipo for the CEO panel. Generate Shared Link produces URL and eight-digit access code distributed via secure channels. Both interviewers successfully join portal using registered names and shared code.",
        "Step six: HR clicks Start for candidate Rovai Mhuri. Panel active_application_id updates. Interviewer portals refresh to show only Rovai. Both interviewers submit marks across seven criteria. HR mark sheet displays each evaluator row and pending status until both submit. Status becomes awaiting screening when complete.",
        "Step seven: HR clicks Start for the next candidate. Interviewers automatically see the new active candidate. Previous candidate remains awaiting screening with complete marks preserved. Process repeats until all interviewed candidates have full evaluator submissions.",
        "Step eight: HR executes Screen Completed Interviews. System verifies all candidates interviewed and all panel marks present, marks candidates completed, returns ranking by average score. HR reviews ranking table showing evaluator count per candidate.",
        "Step nine: HR confirms selection of highest average candidate, updating status to selected. Selected candidate appears in Selected Candidates section for follow-up communication. Activity logs record selection event with timestamp and acting user.",
        "This walkthrough confirms that business rules enforce collaborative evaluation, sequential interviewing, and average-based selection consistent with project objectives.",
    ],
    "Appendix F: Future Enhancement Roadmap": [
        "Phase two enhancements may introduce PostgreSQL relational storage with SQLAlchemy ORM, concurrent transaction support, and indexed queries for large applicant volumes. Phase three may add SMS notifications via gateway integration for interview reminders in regions where email deliverability is inconsistent.",
        "Business intelligence dashboards could visualise funnel metrics from application through screening, interview, and selection stages. Integration with national employment portals could syndicate vacancies automatically. Mobile native applications may be developed once API endpoints are fully extracted from monolithic app structure.",
        "Advanced scoring models incorporating large language models for semantic CV understanding represent a longer-term research direction requiring governance review regarding automated decision-making and bias monitoring.",
    ],
}

METHODOLOGY_SECTION = {
    "2.10 Research and Development Methodology": [
        "The project employed a pragmatic research and development methodology drawing on design science principles: problem identification, artefact design, artefact construction, and evaluation. Each phase produced explicit deliverables assessable against objectives stated in Chapter One. Problem identification combined stakeholder interviews and as-is process documentation. Artefact design encompassed architecture and interface specifications in Chapter Four.",
        "Artefact construction corresponded to Chapter Five implementation activities. Evaluation combined functional testing, usability inspection, and stakeholder demonstration sessions. Feedback loops allowed refinement of interview status rules and interviewer portal refresh behaviour after pilot observations revealed confusion when multiple candidates appeared simultaneously.",
        "The methodology did not adopt pure waterfall execution because some design decisions emerged during implementation when technical constraints became visible. Nevertheless, documentation was updated retrospectively to maintain coherence between analysis, design, and code. This approach aligns with practice in many industrial software projects where incremental discovery is inevitable.",
        "Ethical considerations were observed throughout: applicant data used during testing was anonymised or drawn from consented demonstration profiles; default system passwords were flagged for mandatory change before production; and audit trails were implemented to discourage unauthorised access to curriculum vitae files.",
    ],
}

LIMITATIONS_AND_ETHICS = {
    "1.14 Limitations of the Study": [
        "This study acknowledges several limitations. The prototype employs JSON file storage rather than a production relational database, constraining concurrent write scalability and enterprise backup integrations available in mature database engines. Performance testing under thousands of simultaneous applicants was not exhaustively conducted; response times may require optimisation before national-scale campaigns.",
        "Automated curriculum vitae scoring, while useful, does not capture interpersonal competencies visible only during interviews or practical assessments. The model may undervalue candidates with non-linear career paths or those using terminology differing from job description vocabulary. HR manual review remains essential.",
        "The study focused on a single organisation's requirements; generalisation to other parastatals may require localisation of skill taxonomies, approval workflows, and reporting formats. External validity is therefore contextual rather than universal.",
        "Security evaluation did not include formal third-party penetration testing. Recommendations are based on best practices rather than certified compliance frameworks such as ISO 27001. Production deployment should include independent security assessment.",
        "Long-term maintainability depends on continued availability of developers familiar with Flask and the codebase. Without institutional commitment to maintenance budgets, systems risk obsolescence as dependencies evolve.",
    ],
    "1.15 Ethical Considerations": [
        "Ethical handling of applicant personal data is paramount. Applicants provide information voluntarily for employment consideration. Data should be accessed only by authorised HR personnel for legitimate hiring purposes. Retention policies should define how long unsuccessful applicant records remain stored before secure deletion.",
        "Automated scoring must be monitored for unintended bias against demographic groups correlated with language style or educational institution naming patterns. Periodic review of screening outcomes by gender and regional proxies, where legally permissible, can detect disparities warranting model adjustment.",
        "External interviewers must understand confidentiality obligations regarding candidate information disclosed during sessions. Access codes and links should be distributed through secure channels rather than public social media posts.",
        "Transparency toward applicants about automated processing steps builds trust. Careers portal privacy notices should explain that curriculum vitae may be analysed algorithmically as part of shortlisting support.",
    ],
}

COMPARATIVE_SYSTEMS = {
    "3.12 Comparative Review of Alternative Solutions": [
        "Commercial Applicant Tracking Systems such as global SaaS offerings provide mature feature sets including calendar integrations, offer letter generation, and analytics dashboards. However, subscription costs, data residency considerations, and limited customisation of interview panel workflows motivated exploration of bespoke development for GMB.",
        "Spreadsheet-based tracking remains a low-cost alternative but fails scalability and audit tests at moderate application volumes. Version control issues and formula errors have caused documented hiring mistakes in organisations relying solely on Excel for interview score aggregation.",
        "Enterprise Resource Planning HR modules integrate recruitment with payroll but may require expensive licensing and lengthy configuration cycles unsuitable for rapid deployment of focused recruitment improvements.",
        "The selected bespoke Flask approach optimises fit-to-process and total cost of ownership over multi-year horizons while accepting higher initial development effort borne by this academic project.",
    ],
}

INSTITUTIONAL_CONTEXT = {
    "1.13 Institutional Context of the Grain Marketing Board": [
        "The Grain Marketing Board operates as a pivotal institution within Zimbabwe's agricultural value chain, facilitating grain marketing, storage, and distribution activities that support national food security objectives. Its workforce requirements span technical, managerial, financial, legal, and executive competencies. Recruitment therefore must attract candidates capable of operating in a regulated environment while delivering commercial efficiency and public accountability.",
        "Organisational structure typically includes headquarters functions, regional depots, and specialised units requiring coordinated HR policies. Centralising recruitment data supports workforce planning by revealing which departments generate highest application volumes and longest time-to-fill metrics. Over time, analytics derived from the system could inform training pipelines and graduate recruitment programmes aligned with skill gaps identified during screening.",
        "Public perception of fairness in GMB hiring influences stakeholder trust among farmers, employees, and government oversight bodies. Perceived nepotism or opaque selection undermines morale and may attract negative media attention. Transparent digital workflows do not automatically guarantee fairness but provide auditable evidence that stated procedures were followed, supporting institutional legitimacy.",
        "The board's corporate identity—including logo, colour palette, and communication tone—signals stability and national purpose. Recruitment materials must therefore present a coherent visual identity. The system's branding upload features enable HR to align digital touchpoints with printed annual reports and official stationery without developer intervention for each campaign.",
        "Seasonal and emergency hiring scenarios, such as expansion of storage capacity or policy-driven recruitment drives, stress HR capacity. Automation of application capture and initial CV ranking provides breathing room for officers to focus on stakeholder coordination and interview logistics rather than repetitive data entry.",
        "Collaboration with external experts during senior appointments reflects governance norms requiring independent technical or governance assessment of candidates. The interviewer portal codifies this norm by giving external panelists structured access without permanent system accounts, reducing IT provisioning burden while preserving separation of duties between evaluators and final selectors.",
        "Institutional context also includes compliance with labour laws and public service regulations where applicable. While legal interpretation remains HR management responsibility, the system supports documentary evidence of interview dates, evaluator participation, and selection rationale through logs and mark archives.",
        "Strategic alignment with national digital economy agendas encourages public enterprises to modernise citizen-facing services. An online careers portal extends digital accessibility to job seekers in rural provinces who might otherwise incur travel costs to deliver physical application packets to urban headquarters.",
    ],
}

TECHNICAL_DEEP_DIVE = {
    "5.13 Technical Deep Dive: Key Algorithms and Data Flows": [
        "When an applicant submits a form, Flask receives multipart encoding, validates required fields, checks duplicate email per job, generates application UUID, writes curriculum vitae to uploads directory with sanitised filename prefix, constructs application dictionary with default interview score structures, appends to APPLICATIONS global, and invokes save_applications persisting JSON to disk.",
        "CV scoring begins when HR triggers screening endpoint supplying job identifier. For each pending application, the service resolves resume path, extracts textual content, tokenises job description and CV corpora, computes TF-IDF vectors, measures cosine similarity, evaluates keyword skill lists, aggregates subscores into composite percentage, and writes recommendation text summarising strengths and gaps.",
        "Interview start flow retrieves application by id, validates HR session, calls _set_active_interview updating INTERVIEWER_PANELS JSON with active_application_id and timestamp, iterates other queue members previously in_progress to awaiting_screening if evaluator completion rules satisfied, sets target application in_progress, saves panels and applications, returns enriched JSON consumed by dashboard reload logic.",
        "Score submission flow authenticates user, verifies scoring permission, blocks completed interviews, blocks inactive candidates for interviewer role, reads seven criterion integers clamping to zero-twenty range, sums to raw total, normalises to percentage of 140 maximum, upserts submission array element keyed by scorer_id, recomputes average across submissions updating interview_total and interview_average fields, calls status synchronisation helper, persists data, logs activity.",
        "Screening flow loads all queue members for job, rejects if any remain merely scheduled without interview commencement, rejects if any started candidate lacks full panel submissions listing pending names, marks eligible candidates completed with screened timestamp, sorts enriched results by interview_average descending, returns JSON ranking for HR table rendering.",
        "Selection flow filters completed candidates, sorts by average, groups ties, applies random tiebreak sample when positions insufficient for tied group, updates selected flags and statuses, timestamps selection, logs activity, returns selected candidate summaries for UI confirmation messages.",
        "Interviewer polling flow executes lightweight GET comparing client last known active_changed_at with server panel timestamp; mismatch triggers full page reload ensuring newly started candidate appears without manual refresh by panel members.",
        "These data flows demonstrate tight coupling between business policy and implementation logic, illustrating why requirements analysis and design documentation were prerequisite to coding rather than afterthoughts.",
    ],
}

CHAPTER_DISCUSSIONS = {
    "1.12 Discussion": [
        "The introductory chapter situates the Grain Marketing Board recruitment system within broader discourses on digital transformation in public administration. While many institutions invest in financial and logistics systems first, human capital systems equally determine operational capacity. Delayed modernisation of recruitment infrastructure can create a talent bottleneck that undermines other technology investments by leaving critical posts unfilled or filled with suboptimally assessed candidates.",
        "Stakeholder diversity complicates system design because each group holds different mental models of the hiring process. Applicants conceptualise recruitment as a gateway to employment opportunity. HR professionals view it as a pipeline requiring throughput and compliance. Interviewers experience it as episodic evaluation duty layered atop other professional commitments. Audit actors conceptualise it as a control environment requiring evidence trails. Successful requirements analysis, documented in Chapter Three, depended on articulating these perspectives explicitly rather than assuming a single unified user.",
        "The decision to support external interviewers through shared links and access codes rather than enterprise single sign-on reflects practical constraints common in public-sector IT environments. Panel members may serve once annually; provisioning Active Directory accounts or complex VPN access may be disproportionate. Time-limited tokens balance security with usability, though organisations must operationalise procedures for regenerating expired links without delaying selection timelines.",
        "Institutional vision and mission statements are sometimes criticised as ornamental corporate communications detached from daily practice. In this project, they were utilised as design tests: does a proposed feature advance transparency, fairness, or service excellence? If not, its priority was lowered. This values-driven filtering prevented feature bloat while keeping development aligned with organisational identity.",
        "Chapter One concludes that the problem domain is well bounded, the aim is achievable with selected technologies, and justification is compelling on operational and governance grounds. Readers should proceed to Chapter Two with clarity regarding what the system must accomplish and why those accomplishments matter to the Grain Marketing Board and its stakeholders.",
    ],
    "2.11 Discussion of Planning Outcomes": [
        "Planning outcomes exceeded minimal documentation thresholds by producing artefacts reusable in future institutional projects. The stakeholder matrix template can be reapplied to other system initiatives. The risk register format provides a starting point for operational risk reviews once the recruitment platform enters production service.",
        "Timeline compression inherent in academic calendars forced explicit prioritisation. Features classified as could-have, such as advanced analytics widgets and SMS integration, were deferred without guilt because must-have hiring workflows remained intact. This experience illustrates portfolio management skills transferable to professional project management roles.",
        "Resource planning identified single-developer dependency as a concentration risk. Knowledge transfer through comprehensive documentation and modular code structure mitigates bus factor concerns should maintenance responsibility transfer to another developer or vendor.",
    ],
    "3.11 Discussion of Analytical Findings": [
        "Analytical findings confirm that the as-is recruitment environment exhibited classic symptoms of manual process maturity gaps: duplicated data stores, informal communication channels for critical decisions, and limited metrics. The to-be process model introduces measurable states and transitions enabling future key performance indicators such as median days from application to interview and evaluator submission latency.",
        "Requirements prioritisation debates surfaced tension between comprehensiveness and deliverability. HR stakeholders naturally requested extensive reporting; analysis clarified that hiring integrity features—multi-evaluator marks, screening guards, audit logs—were non-negotiable whereas decorative dashboard charts were negotiable. Documenting these negotiations preserves institutional memory supporting scope decisions.",
        "Data analysis revealed that interview score submissions represent first-class entities rather than ephemeral form posts. Treating them as persistent sub-records with scorer identity enables both average computation and post-hoc reviewer inspection, a key audit capability.",
    ],
    "4.12 Discussion of Design Decisions": [
        "Architectural choice of monolithic Flask application versus microservices involved trade-offs. Microservices could separate CV scoring and email services for independent scaling but would introduce deployment orchestration overhead unsuitable for initial prototype hosting. Monolithicity accelerated development while internal modularisation preserved seams for future extraction.",
        "User interface design decisions prioritised familiarity over novelty. HR users accustomed to spreadsheet-like tables received mark sheets resembling grids rather than unconventional visualisations requiring training. Interviewers received single-candidate focus views mirroring boardroom sequence rather than overwhelming multi-candidate dashboards.",
        "Security design accepts that perfect security is unattainable; goal was reasonable diligence. Hashed passwords, role checks, expiring interviewer tokens, and HTTP security headers raise the difficulty of casual abuse without claiming elimination of determined adversaries. Production deployment must complement application controls with network firewalls and TLS.",
    ],
    "5.12 Discussion of Implementation Experience": [
        "Implementation experience reinforced that backend business rules deliver institutional value more visibly than cosmetic tweaks. Correcting interview completion logic produced more stakeholder satisfaction than colour adjustments because it directly affected hiring integrity perceptions.",
        "Testing revealed edge cases such as duplicate surnames among interviewers requiring HR to disambiguate accounts during registration. The system responds with ambiguous name errors directing users to contact HR rather than silently authenticating the wrong person.",
        "Developer reflection suggests early investment in enrichment functions like _enrich_application paid dividends by ensuring templates and JSON APIs present consistent computed fields, reducing duplication bugs across HR and interviewer views.",
        "Overall implementation confidence is high for prototype deployment in pilot recruitment campaigns. Production hardening remains necessary, particularly database migration, automated backup verification, and formal penetration testing beyond scope of this academic project.",
    ],
}

IMPLEMENTATION_DETAILS = {
    "5.10 Code Quality and Maintainability Practices": [
        "Maintainability was supported through descriptive function naming such as _enrich_application, _all_required_scorers_submitted, and _set_active_interview, which communicate intent to future maintainers. Permission helpers _require_hr, _require_hr_admin, _require_scoring_permission, and _require_screening_permission centralise authorisation logic avoiding duplicated role checks across dozens of routes.",
        "Data migration logic embedded in load_all_data demonstrates defensive schema evolution: when new fields such as interview_score_submissions or panel access_code appear in later versions, legacy JSON files gain default values on startup preventing runtime KeyError exceptions. This pattern suits prototype JSON storage; production relational migrations would utilise versioned migration scripts.",
        "Template organisation separates applicant, HR, interviewer, and audit views reducing merge conflicts during parallel edits. Stylesheet centralisation in static/style.css promotes consistent typography and spacing. JavaScript functions embedded in hr_dashboard.html handle modal dialogs, interviewer link generation, and marks table rendering; future refactoring could extract these into static JS modules.",
    ],
    "5.11 Training and Change Management Recommendations": [
        "Successful organisational adoption requires HR training workshops covering job publication, screening execution, interview scheduling, external interviewer onboarding, mark review, and selection confirmation. Quick-reference cards summarising interviewer sign-in steps should accompany panel invitation emails.",
        "IT administrators require documentation for environment variable configuration, backup procedures, and log file locations. Change management should designate an HR system champion to field user questions during initial live recruitment campaigns.",
    ],
}
